### PR TITLE
update neo4j gem depenency to ~> 6.0

### PR DESCRIPTION
**Pull request by aijcoa**

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Pessimistic requires (like `~>`) are great for apps, though in a gem I think it would be best to use `>= 3.0.1` since I'm pretty sure that it works for all versions between 3 and 6.

That said, thanks so much for taking note of this!  I'll make the `>=` change now

**Comment by cheerfulstoic** [comment]
Just realized I don't own the gem.  @subvertallchris ?

**Comment by subvertallchris** [comment]
My bad, thought you did. I'll do the release and give you access tomorrow
morning, I won't be back on my computer tonight.

**Comment by cheerfulstoic** [comment]
:metal: thanks ;)

**Pull request merged**
